// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
// dotenv: el CLI no carga .env automáticamente al correr bajo Node (`bunx prisma ...`).
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
